la_goodmorning:
  alias: 'LA - Good morning!'
  sequence:
    - service: light.turn_on
      entity_id: light.la_lightstrip
      data:
        effect: "Sunrise 1min"
    - delay: 00:00:30
    - service: light.turn_on
      entity_id: light.la_nachttisch
      data:
        effect: "Sunrise 1min"
    - delay: 00:01:00
    - service: light.turn_off
      entity_id: light.la_lightstrip
