- platform: template
  sensors:
    vacuum_start_time_weekdays:
      friendly_name: 'Staubsauger Start'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.vacuum_start_hour_weekdays") | int, states("input_number.vacuum_start_minutes_weekdays") | int) }}'
    vacuum_start_time_weekend:
      friendly_name: 'Staubsauger Start (Weekend)'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.vacuum_start_hour_weekend") | int, states("input_number.vacuum_start_minutes_weekend") | int) }}'
    vacuum_status:
      friendly_name: "Staubsauger - Status"
      value_template: "{{ states.vacuum.julio.attributes.status }}"
    vacuum_weekdays:
      friendly_name: "Staubsauger - Weekdays"
      value_template: "Weekdays:"
    vacuum_battery:
      friendly_name: "Staubsauger - Battery"
      value_template: "Battery: {{ states.vacuum.julio.attributes.battery_level }}"
      device_class: battery
      unit_of_measurement: '%'
    vacuum_accessories:
      friendly_name: "Staubsauger - Zubehör"
      value_template: "Zubehör"
    vacuum_operation:
      friendly_name: "Staubsauger - Betrieb"
      value_template: "Betrieb"
    vacuum_main_brush:
      friendly_name: "Staubsauger - Mainbrush"
      value_template: "Mainbrush: {{ states.vacuum.julio.attributes.main_brush_left }} h"
    vacuum_side_brush:
      friendly_name: "Staubsauger - Sidebrush"
      value_template: "Sidebrush: {{ states.vacuum.julio.attributes.side_brush_left }} h"
    vacuum_filter:
      friendly_name: "Staubsauger - Filter"
      value_template: "Filter: {{ states.vacuum.julio.attributes.filter_left }} h"
    vacuum_sensor:
      friendly_name: "Staubsauger - Dirt left"
      value_template: "Dirt left: {{ states.vacuum.julio.attributes.sensor_dirty_left }} h"