homeassistant:
  # Name of the location where Home Assistant is running
  name: HQ

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 504
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Zurich
  # Customization file
  customize: !include customize.yaml
  #Path Access
  allowlist_external_dirs:
    - '/tmp'

# Includes
automation: !include automations.yaml #!include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
scene: #!include scenes.yaml
sensor: !include_dir_merge_list sensors/
yeelight: !include lights/xiaomi-yeelights.yaml
light: !include lights/lights.yaml
group: !include groups.yaml
input_boolean: !include misc/input_boolean.yaml
input_number: !include misc/input_number.yaml
input_datetime: !include misc/input_datetime.yaml

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/
      
# Enables configuration UI
config:

# System Überwachung
system_health:

# lovelace in YAML
lovelace:
  mode: yaml
  resources:
    [ {url: /hacsfiles/bar-card/bar-card.js,                                  type: module},
      {url: /hacsfiles/button-card/button-card.js,                            type: module},
      {url: /hacsfiles/lovelace-ha-dashboard/ha-dashboard.js,                 type: module},
      {url: /hacsfiles/lovelace-card-mod/card-mod.js,                         type: module},
      {url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js,             type: module},
      {url: /hacsfiles/lovelace-layout-card/layout-card.js,                   type: module},
      {url: /hacsfiles/sidebar-card/sidebar-card.js,                          type: module}]

  
# Shelly Komponente 
shelly: !include shelly.yaml

# Sun tracking
sun:

# Recoreder (History)
recorder:
  purge_keep_days: 365
  exclude:
    domains:
      - media_player
      - weblink
      - updater
      - group
      - script
      - sun
      - zone
    entities:
      - sensor.date
      - sensor.date_time
      - sensor.time
      - sensor.time_date
      - sensor.time_to_alarm
      - sensor.time_to_alarm_min
      - sensor.time_utc
  
# Enables support for tracking state changes over time
history:

# HA Cloud
cloud:
  alexa:
    filter:
      include_domains:
        - sensor
        - switch
        - light
        - script
        - input_boolean
        - binary_sensor

# Web Konfiguration 
http:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:


# App Functions
mobile_app:

# Wetter
weather:
  - platform: darksky
    api_key: !secret darksky_key
    mode: daily
